baseURL = "https://macmade.dev/"
languageCode = "de"
title = "macmade.dev"
theme = "blowfish"
enableRobotsTXT = true
defaultContentLanguage = "de"
[pagination]
  pagerSize = 10
[params]
  colorScheme = "auto"    # dark/light auto
  enableSearch = true
  showReadingTime = true
  showShareButtons = false
  enableCodeCopy = true   # Copy-Code Button ✔️
  theme = "blowfish"
