baseURL = "https://macmade.dev/"
title = "macmade.dev"
theme = "PaperMod"
languageCode = "de"
defaultContentLanguage = "de"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

  
copyright = "&copy; 2025 macmade.dev &middot; <a href='/impressum/'>Impressum</a> &middot; <a href='/datenschutz/'>Datenschutz</a>"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true       # Zeilennummern anzeigen
    style = "monokai"    # Oder "dracula", "github" etc.
    tabWidth = 4
[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON ist wichtig für den Suchindex

[params]
  defaultTheme = "auto" # Erkennt System Dark/Light automatisch
  description = "Notizen zu Code, Mac, Proxmox, Docker und LLms und alles was so anfällt"
  # HIER muss es stehen (HTML ist erlaubt):
  author = "Matthias Hartmann"
  ShowCodeCopyButtons = true
  ShowShareButtons = false
    
  [params.profileMode]
    enabled = true
    title = "macmade.dev"
    subtitle = "Der Zettelkasten für Code, .net, Proxmox, Docker, Mac und alles was so anfällt"
    imageUrl = "avatar.jpg" # Sucht in /static/
    imageTitle = "Matthias Hartmann"
    imageWidth = 150
    imageHeight = 150
    
    [[params.profileMode.buttons]]
      name = "Zettelkasten"
      url = "/posts"
    
   
[[menu.main]]
  identifier = "posts"
  name = "Beiträge"
  url = "/posts/"
  weight = 10
[[menu.main]]
  identifier = "search"
  name = "Suche"
  url = "/search/"
  weight = 5

 