baseURL = "https://macmade.dev/"
title = "macmade.dev"
theme = "PaperMod"
languageCode = "de"
defaultContentLanguage = "de"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true       # Zeilennummern anzeigen
    style = "monokai"    # Oder "dracula", "github" etc.
    tabWidth = 4

[params]
  defaultTheme = "auto" # Erkennt System Dark/Light automatisch
  description = "Mac · .NET · Docker · Proxmox · Automatisierung"
  author = "Matthias Hartmann"
  ShowCodeCopyButtons = true
  ShowShareButtons = true
   
  [params.profileMode]
    enabled = true
    title = "macmade.dev"
    subtitle = "Softwareentwicklung · Mac · .NET · Docker · Proxmox"
    imageUrl = "avatar.jpg" # Sucht in /static/
    imageTitle = "Matthias Hartmann"
    imageWidth = 150
    imageHeight = 150
    
    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/posts"
    
   
[[menu.main]]
  identifier = "posts"
  name = "Beiträge"
  url = "/posts/"
  weight = 10

# Das Footer-Menü
[[menu.footer]]
  identifier = "impressum"
  name = "Impressum"
  url = "/impressum/"
  weight = 10

[[menu.footer]]
  identifier = "datenschutz"
  name = "Datenschutz"
  url = "/datenschutz/"
  weight = 20