baseURL = "https://macmade.dev/"
title = "macmade.dev"
theme = "PaperMod"
languageCode = "de"
defaultContentLanguage = "de"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true       # Zeilennummern anzeigen
    style = "monokai"    # Oder "dracula", "github" etc.
    tabWidth = 4

[params]
  defaultTheme = "auto" # Erkennt System Dark/Light automatisch
  description = "Notizen zu Code, Mac, Proxmox, Docker und LLms und alles was so anfällt"
  author = "Matthias Hartmann"
  ShowCodeCopyButtons = true
  ShowShareButtons = true
   
  [params.profileMode]
    enabled = true
    title = "macmade.dev"
    subtitle = "Der Zettelkasten für Code, .net, Proxmox, Docker, Mac und alles was so anfällt"
    imageUrl = "avatar.jpg" # Sucht in /static/
    imageTitle = "Matthias Hartmann"
    imageWidth = 150
    imageHeight = 150
    
    [[params.profileMode.buttons]]
      name = "Zettelkasten"
      url = "/posts"
    
   
[[menu.main]]
  identifier = "posts"
  name = "Beiträge"
  url = "/posts/"
  weight = 10

# Das Footer-Menü
[[menu.footer]]
  identifier = "impressum"
  name = "Impressum"
  url = "/impressum/"
  weight = 10

[[menu.footer]]
  identifier = "datenschutz"
  name = "Datenschutz"
  url = "/datenschutz/"
  weight = 20